### ISSUE TITLE
run_analyzer bug

### ISSUE THREAD

**Issue by rusu24edward** [ABM4ALL/Melodie#4] opened 2023-02-01 21:02 UTC
Similar to #3 

`python3 run_analyzer.py` returns the following error:

```
Traceback (most recent call last):
  File "run_analyzer.py", line 7, in <module>
    analyzer.plot_health_state_share(id_scenario=0)
  File "/Users/rusu1/tmp/CovidContagion/source/analyzer.py", line 24, in plot_health_state_share
    df = self.db.read_dataframe("environment_result")
  File "/Users/rusu1/tmp/Melodie/v_melodie/lib/python3.7/site-packages/MelodieInfra/db/db.py", line 193, in read_dataframe
    return pd.read_sql(sql, self.connection)
  File "/Users/rusu1/tmp/Melodie/v_melodie/lib/python3.7/site-packages/pandas/io/sql.py", line 599, in read_sql
    pandas_sql = pandasSQL_builder(con)
  File "/Users/rusu1/tmp/Melodie/v_melodie/lib/python3.7/site-packages/pandas/io/sql.py", line 788, in pandasSQL_builder
    return SQLDatabase(con, schema=schema, meta=meta)
  File "/Users/rusu1/tmp/Melodie/v_melodie/lib/python3.7/site-packages/pandas/io/sql.py", line 1410, in __init__
    meta = MetaData(self.connectable, schema=schema)
TypeError: __init__() got multiple values for argument 'schema'
```

**Comment by rusu24edward** [comment] 2023-02-01 22:01
https://github.com/openjournals/joss-reviews/issues/5100

**Comment by hzyrc6011** [comment] 2023-02-02 09:04
There is an error in our docs that Melodie is suitable for python>=3.8, not python>=3.7, so it is better to use python 3.8 or newer to test this program.

Besides, this problem is very likely caused by error in  the version for sqlalchemy. Would you mind using this command:

```sh
python -m pip install sqlalchemy==1.4.41
```
to install the older sqlalchemy version and re-run the program?

**Comment by SongminYu** [comment] 2023-03-04 09:37
Hi @rusu24edward, we have fixed this issue and also updated the installation document: Python >= 3.8 ([link](https://abm4all.github.io/Melodie/html/installation.html#user-installation)). Do you find other bugs? If not, you could also close this issue. Thanks!

**Closed** 2023-03-06 20:59 UTC
