### ISSUE TITLE
run_simulation bug

### ISSUE THREAD

**Issue by rusu24edward** [ABM4ALL/Melodie#3] opened 2023-02-01 20:59 UTC
Reviewing the [Joss Submission](https://github.com/openjournals/joss-reviews/issues/5100), I am attempting to run the tutorials. I installed Melodie as per the installation instructions, and then ran `python3 run_simulator.py`. I get the following error in all of the tutorials:

```
Traceback (most recent call last):
  File "run_simulator.py", line 14, in <module>
    simulator.run()
  File "/Users/rusu1/tmp/Melodie/v_melodie/lib/python3.7/site-packages/Melodie/simulator.py", line 236, in run
    self.pre_run()
  File "/Users/rusu1/tmp/Melodie/v_melodie/lib/python3.7/site-packages/Melodie/simulator.py", line 99, in pre_run
    create_db_conn(self.config).clear_database()
  File "/Users/rusu1/tmp/Melodie/v_melodie/lib/python3.7/site-packages/MelodieInfra/db/db.py", line 122, in clear_database
    logger.info(f"Database contains tables: {self.connection.table_names()}.")
AttributeError: 'Engine' object has no attribute 'table_names'
```

I also get this error from `run_calibrator.py` in the CovidContagionCalibrator tutorial.
I also get this error from `run_trainer.py` in the RockPaperScissorsTrainer tutorial.

**Comment by rusu24edward** [comment] 2023-02-01 21:04
I also get this error with ABMFrameworkComparison run_simulator

**Comment by hzyrc6011** [comment] 2023-02-02 09:04
There is an error in our docs that Melodie is suitable for python>=3.8, not python>=3.7, so it is better to use python 3.8 or newer to test this program.

Besides, this problem is very likely caused by error in the version for sqlalchemy. Would you mind using this command:
```
python -m pip install sqlalchemy==1.4.41
```
to install the older sqlalchemy version and re-run the program?

**Comment by JoelForamitti** [comment] 2023-02-15 09:11
I had the same issue (using Python 3.10.6) and installing sqlalchemy==1.4.41 as proposed above solved the issue. I would suggest to either fix this in the package requirements or ideally to support the latest version of sqlalchemy.

**Comment by rusu24edward** [comment] 2023-02-16 23:53
I tried again with Python 3.8.9. Here is my virtual environment:
```
astunparse        1.6.3
chardet           5.1.0
cloudpickle       2.2.1
contourpy         1.0.7
cycler            0.11.0
Cython            3.0.0a10
et-xmlfile        1.1.0
fonttools         4.38.0
greenlet          2.0.2
kiwisolver        1.4.4
matplotlib        3.6.3
Melodie           0.6.0
networkx          3.0
numpy             1.24.2
openpyxl          3.1.1
packaging         23.0
pandas            1.5.3
Pillow            9.4.0
pip               23.0
plumbum           1.8.1
pprintast         1.2.1
pyparsing         3.0.9
python-dateutil   2.8.2
pytz              2022.7.1
rpyc              5.3.0
scikit-opt        0.6.6
scipy             1.10.0
seaborn           0.12.2
setuptools        49.2.1
six               1.16.0
SQLAlchemy        2.0.3
typing_extensions 4.4.0
websockets        10.4
wheel             0.38.4
```

I get the same error.

I also did it by installing Melodie according to the developer installation docs. Same error.

---

Following your instructions to install sqlalchemy==1.4.41, I am able to run the tutorials using both python3.7 and python3.8 whether I install directly from pip or according to the developer's installation.

**Comment by hzyrc6011** [comment] 2023-02-23 08:59
It is fixed now at the master branch, we modified the dependencies now, thanks!

**Comment by SongminYu** [comment] 2023-03-04 09:34
Hi @rusu24edward, we have fixed this dependency issue. Do you find other bugs? If not, you could also close this issue.

**Closed** 2023-03-06 20:57 UTC
